### PR TITLE
added buy token button and updated logos

### PR DESCRIPTION
**Pull request by larrotiz**
Changed the favicon, navbar logo, and logo at bottom of page. Added buy $MOONEY button that links to uniswap. Updated headline text to be a little more exciting.

### CODE REVIEW

**Review by dissentertainer — APPROVED** [review]

**Comment by irquintanas** [comment]
Hi! @dissentertainer do you know how this changes may appear in the locale files so that we can proceed to update the translation?

**Comment by dissentertainer** [comment]
@irquintanas I think we just need to update line 351 of this file to say "Buy $MOONEY" and then update the translation on line 352.

I also noticed that the word "Governance" in the top isn't translated into Spanish, so you will need to update that in this file as well:

**Comment by irquintanas** [comment]
Hey thanks @dissentertainer, very easy to make changes this way! Already created both commits. What I don't seem to find is the line with the new heading "We are sending MoonDAO members..."
image

**Comment by dissentertainer** [comment]
@irquintanas That text used to say "Send a MoonDAO member to space." It just needs the message and translation to be updated here on line 291 of `/es/code.json`.
https://github.com/Official-MoonDao/moondaowww/blob/main/i18n/es/code.json#L291

**Comment by irquintanas** [comment]
Done... Thanks @dissentertainer!

**Pull request merged**
